# docker-compose.yml #
version: "3.4"
services:
  mysql:
    image: mysql
    volumes: 
      - mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=urlshort
      - MYSQL_DATABASE=url_shortener
  web:
    build:
      dockerfile: Dockerfile.web.dev
      context: .
    #image: php:alpine
    volumes:
      - "./:/app"
      - "/app/src/vendor"
      - web_root_home:/root
    working_dir: /app/src/
    command: "php artisan serve --host=0.0.0.0 --port=7999"
    ports:
      - 8000:7999
    depends_on:
      - mysql
volumes:
  mysql_db:
  web_root_home:
